# Generated by Django 3.2.4 on 2021-11-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=240, null=True)),
                ('capacidad', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('ubicacion', models.CharField(max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AulaXCongreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('sede', models.IntegerField()),
                ('año', models.IntegerField()),
                ('chairPrincipal', models.CharField(max_length=255, null=True)),
                ('coordLocal', models.CharField(max_length=255, null=True)),
                ('fechaInCongreso', models.DateTimeField(null=True)),
                ('fechaFinCongreso', models.DateTimeField(null=True)),
                ('fechaLimPapers', models.DateTimeField(null=True)),
                ('fechaProrrogaPapers', models.DateTimeField(null=True)),
                ('fechaFinEvaluacion', models.DateTimeField(null=True)),
                ('fechaFinReEv', models.DateTimeField(null=True)),
                ('fechaFinInsTemprana', models.DateTimeField(null=True)),
                ('fechaFinInsTardia', models.DateTimeField(null=True)),
                ('fechaCierreCongreso', models.DateTimeField(null=True)),
                ('modalidad', models.CharField(max_length=240, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_id', models.CharField(max_length=255, null=True)),
                ('task_id_aviso_chair', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('calle', models.CharField(max_length=240)),
                ('numero', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simposio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimposiosxCongreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
