# Generated by Django 3.2.4 on 2021-11-09 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congresos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simposiosxcongreso',
            name='idChair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simposiosxcongreso',
            name='idCongreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.congreso'),
        ),
        migrations.AddField(
            model_name='simposiosxcongreso',
            name='idSimposio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.simposio'),
        ),
        migrations.AddField(
            model_name='sede',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.localidad'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='congresos.pais'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.provincia'),
        ),
        migrations.AddField(
            model_name='aulaxcongreso',
            name='idAula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.aula'),
        ),
        migrations.AddField(
            model_name='aulaxcongreso',
            name='idCongreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.congreso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='congresos.sede'),
        ),
    ]
