# Generated by Django 3.2.4 on 2021-11-09 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('congresos', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simposiosxevaluador',
            name='idSimposio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congresos.simposio'),
        ),
    ]
